### ISSUE TITLE
after using this library and push app to live it thorws error "This video player is not supported"

### ISSUE THREAD

**Issue by ahmadarslan13** [khizar1556/MKVideoPlayer#10]

**Comment by ahmadarslan13** [comment]
In debug mode it is working perfectly fine

**Comment by sayberwar** [comment]
I also have this problem.

**Comment by VivekChodvadiya** [comment]
android:hardwareAccelerated="true"

and 

in app build file
 release {
            minifyEnabled false
            debuggable false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }


 add this line in application module
