### ISSUE TITLE
Not working in fragment

### ISSUE THREAD

**Issue by apurvthakkar99** [khizar1556/MKVideoPlayer#17]
When I try to initialize 
mkplayer = new  MKPlayer(getActivity()); in fragment it is returning null videoView

 videoView = (IjkVideoView) activity.findViewById(R.id.video_view);

here I am getting videoView as null.

**Comment by naeimsafaee** [comment]
Hey , put line below in onResume method of your fragment .

mkplayer = new MKPlayer(getActivity());
:)
