### ISSUE TITLE
Video Folders are not shown in this app.

### ISSUE THREAD

**Issue by ejaz1626** [khizar1556/MKVideoPlayer#4]
Please, add this function to show all videos folders in this app.
Just Like MX Player, When this app is launched, all the video folders are shown first and then
click on any folder to show videos and play any video. Here is screenshot attached.
![screenshot_2018-12-14-18-30-49](https://user-images.githubusercontent.com/11348759/50042722-0cfdf400-0089-11e9-8cc2-257ca55fa94b.png)

**Comment by khizar1556** [comment]
we'll add it soon
