### ISSUE TITLE
on orientation its again playing the video from start why?

### ISSUE THREAD

**Issue by AbdulRehmanAB** [khizar1556/MKVideoPlayer#9]
MKPlayer mkplayer;
    public ArrayList<Model_Video> al_video;
    int playPosition =0;
    Context context;
    SharedPreferences.Editor prefsEditor;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        requestWindowFeature(Window.FEATURE_NO_TITLE); //will hide the title
        getSupportActionBar().hide(); // hide the title bar
        this.getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN,
                WindowManager.LayoutParams.FLAG_FULLSCREEN); //enable full screen
        setContentView(R.layout.activity_mkplayer);

        mkplayer = new MKPlayer(this);
        Bundle b = getIntent().getExtras();

        if (null != b) {
            al_video = (ArrayList<Model_Video>) b.get("array_list");
            playPosition = Integer.parseInt((String) b.get("p"));
        }

        mkplayer.onComplete(new Runnable() {
            @Override
            public void run() {
                //callback when video is finish
                Toast.makeText(getApplicationContext(), "video completed",Toast.LENGTH_SHORT).show();
            }
        }).onInfo(new MKPlayer.OnInfoListener() {
            @Override
            public void onInfo(int what, int extra) {
                switch (what) {
                    case IMediaPlayer.MEDIA_INFO_BUFFERING_START:
                        //do something when buffering start
                        break;
                    case IMediaPlayer.MEDIA_INFO_BUFFERING_END:
                        //do something when buffering end
                        break;
                    case IMediaPlayer.MEDIA_INFO_NETWORK_BANDWIDTH:
                        //download speed
                        break;
                    case IMediaPlayer.MEDIA_INFO_VIDEO_RENDERING_START:
                        //do something when video rendering
                        break;
                }
            }
        }).onError(new MKPlayer.OnErrorListener() {
            @Override
            public void onError(int what, int extra) {
                Toast.makeText(getApplicationContext(), "video play error",Toast.LENGTH_SHORT).show();
            }
        });
        mkplayer.setPlayerCallbacks(new MKPlayer.playerCallbacks() {
            @Override
            public void onNextClick() {
                int arr_size = al_video.size() - 1;
                playPosition=playPosition<arr_size?playPosition+1:arr_size;
                mkplayer.play(al_video.get(playPosition).getStr_path());
            }

            @Override
            public void onPreviousClick() {
                playPosition=playPosition-1<0?0:playPosition-1;
                mkplayer.play(al_video.get(playPosition).getStr_path());
            }
        });

        mkplayer.play(al_video.get(playPosition).getStr_path());

    }

    @Override
    protected void onPause() {
        super.onPause();
        if (mkplayer != null) {
            mkplayer.onPause();
        }
    }

    @Override
    protected void onResume() {
        super.onResume();
        if (mkplayer != null) {
            mkplayer.onResume();
        }
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(getApplicationContext());
        SharedPreferences.Editor editor = prefs.edit();
        editor.putString("videokey",Integer.toString(playPosition));
        editor.apply();

        if (mkplayer != null) {
            mkplayer.onDestroy();
        }
    }

    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        if (mkplayer != null) {
            mkplayer.onConfigurationChanged(newConfig);
        }
    }

    @Override
    public void onBackPressed() {
        SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(getApplicationContext());
        SharedPreferences.Editor editor = prefs.edit();
        editor.putString("videokey",Integer.toString(playPosition));
        editor.apply();
        if (mkplayer != null && mkplayer.onBackPressed()) {
            return;
        }
        super.onBackPressed();
    }
}

**Comment by nmghelani** [comment]
I think you forgot to add configChanges in manifest in activity tab like below:
`android:configChanges="keyboardHidden|orientation|screenSize"`

**Comment by ranakhizar1556** [comment]
Fixes #9
